/* ============================================================
   SHARED PROJECT DATA
   Used by: script.js (work grid), gallery.js (mockups),
            project.js (case study page)
   ============================================================ */

export const PROJECTS_LIST = [
  { id: 'inklab', title: 'InkLab',    tag: 'AI Tattoo Studio · Mobile',    year: '2025', color: '#B17FFF', emoji: '🎨', desc: 'An AI-powered tattoo studio app for the Vietnamese market — design-system-driven UI with a flow that turns inspiration into booked appointments.' },
  { id: 'aura',   title: 'Aura',      tag: 'Emotional Wellness · Mobile',   year: '2025', color: '#3ECFBF', emoji: '✨', desc: 'A gamified emotional-wellness app with an animated AI companion and an energy/store economy, balancing playful mechanics with a calm layout.' },
  { id: 'pulse',  title: 'Pulse',     tag: 'Analytics Dashboard · Web',     year: '2024', color: '#4D96FF', emoji: '📊', desc: 'A Mixpanel-style analytics dashboard — dense data made legible through clear hierarchy and an editorial case study for developer handoff.' },
  { id: 'thoroi', title: 'Thợ Ơi!',  tag: 'Home Services · Mobile',        year: '2024', color: '#FF6B6B', emoji: '🔧', desc: 'A Vietnamese home-repair booking app. A full Nielsen heuristic audit drove a redesign of five core screens — lower friction from search to booking.' },
];

export const MOCKUPS_LIST = [
  { id:'inklab-1', project:'InkLab',   screen:'Discovery Feed',    category:'mobile', type:'phone',   bg:'linear-gradient(145deg,#B17FFF 0%,#7C3AED 100%)', desc:'The main discovery feed — users explore AI-generated tattoo styles, curated collections, and trending designs.',             tags:['Mobile','Feed UI','AI'] },
  { id:'inklab-2', project:'InkLab',   screen:'AI Generation',     category:'mobile', type:'phone',   bg:'linear-gradient(145deg,#8B5CF6 0%,#4C1D95 100%)', desc:'AI prompt input and generation screen — users describe their vision and the AI produces multiple tattoo concepts.',             tags:['Mobile','AI Flow','Prompt UI'] },
  { id:'aura-1',   project:'Aura',     screen:'Daily Check-in',    category:'mobile', type:'phone',   bg:'linear-gradient(145deg,#3ECFBF 0%,#0D9488 100%)', desc:'Daily emotional check-in with animated AI companion. Mood logging, streak tracking, and today\'s wellness goal.',           tags:['Mobile','Wellness','Gamification'] },
  { id:'aura-2',   project:'Aura',     screen:'Companion Chat',    category:'mobile', type:'phone',   bg:'linear-gradient(145deg,#6EE7B7 0%,#059669 100%)', desc:'Conversational interface with the AI companion — supportive, context-aware, and designed to feel warm rather than clinical.', tags:['Mobile','Chat UI','Emotion'] },
  { id:'pulse-1',  project:'Pulse',    screen:'Dashboard Overview',category:'web',    type:'browser', bg:'linear-gradient(145deg,#4D96FF 0%,#2563EB 100%)', desc:'Main analytics dashboard: KPI cards, time-series charts, funnel breakdown, and live activity feed — all in one glance.',    tags:['Web','Dashboard','Data Viz'] },
  { id:'pulse-2',  project:'Pulse',    screen:'Report Builder',    category:'web',    type:'browser', bg:'linear-gradient(145deg,#60A5FA 0%,#1D4ED8 100%)', desc:'Drag-and-drop report builder for custom analytics views. Block-based system inspired by Notion, adapted for data.',        tags:['Web','Builder UI','Complex UX'] },
  { id:'thoroi-1', project:'Thợ Ơi!', screen:'Service Search',    category:'mobile', type:'phone',   bg:'linear-gradient(145deg,#FF6B6B 0%,#DC2626 100%)', desc:'Smart search with category filters, geo-proximity sorting, and real-time availability badges — redesigned after audit.',   tags:['Mobile','Search UX','Vietnam'] },
  { id:'thoroi-2', project:'Thợ Ơi!', screen:'Booking Flow',      category:'mobile', type:'phone',   bg:'linear-gradient(145deg,#FF9F1C 0%,#D97706 100%)', desc:'Streamlined 3-step booking flow: pick slot → confirm → pay. Removed 4 redundant screens to cut drop-off.',              tags:['Mobile','Conversion','Forms'] },
];

export const PROJECTS_DETAIL = {
  inklab: {
    id: 'inklab',
    title: 'InkLab',
    emoji: '🎨',
    tagline: 'AI-Powered Tattoo Studio App',
    category: 'Mobile · iOS & Android',
    year: '2025',
    role: 'Product Designer — end-to-end',
    duration: '3 months',
    color: '#B17FFF',
    colorPale: '#EEE2FF',
    tools: ['Figma', 'FigJam', 'Prototyping', 'Design System', 'User Research'],
    overview: 'InkLab is an AI-powered tattoo studio app for the Vietnamese market. Users describe or sketch their tattoo idea, the AI generates multiple concepts, and they can book a session with a vetted local artist — all in one seamless flow.',
    problem: 'Getting a tattoo in Vietnam involves endless scrolling through Instagram, DMing artists who may not respond for days, and hoping the consultation aligns with your vision. There is no structured discovery-to-booking pipeline, and the visual communication gap between client and artist causes frustration on both sides.',
    solution: 'A design-system-driven mobile app that uses AI generation to bridge the inspiration gap, paired with a streamlined booking flow that reduces time-to-appointment from days to under 10 minutes.',
    process: [
      { step: '01', label: 'Research',  icon: '🔍', desc: 'Interviewed 12 tattoo enthusiasts and 5 local artists. Journey-mapped the full flow from "I want a tattoo" to "appointment booked."' },
      { step: '02', label: 'Define',    icon: '📋', desc: 'Core pain point: lack of visual language between client and artist. Reframed the problem as a communication design challenge, not just a booking problem.' },
      { step: '03', label: 'Ideate',    icon: '💡', desc: 'Ran 2 design sprints. Explored chat-first, visual-first, and AI-guided interaction models. Chose visual-first based on user preference testing.' },
      { step: '04', label: 'Design',    icon: '✏️', desc: 'Built a full Figma design system: 120+ components, 4 breakpoints, dark/light modes. Delivered 42 final screens with interactive prototype.' },
      { step: '05', label: 'Test',      icon: '🧪', desc: 'Usability-tested with 8 participants. Iterated on the AI generation screen 3× based on observed confusion patterns before finalising.' },
    ],
    screens: [
      { name: 'Onboarding',      bg: 'linear-gradient(145deg,#C084FC,#7C3AED)', type: 'phone' },
      { name: 'Discovery Feed',  bg: 'linear-gradient(145deg,#B17FFF,#6D28D9)', type: 'phone' },
      { name: 'AI Generation',   bg: 'linear-gradient(145deg,#8B5CF6,#4C1D95)', type: 'phone' },
      { name: 'Artist Profile',  bg: 'linear-gradient(145deg,#A78BFA,#5B21B6)', type: 'phone' },
    ],
    outcomes: [
      { metric: '42',   label: 'Screens designed' },
      { metric: '120+', label: 'Design system components' },
      { metric: '92%',  label: 'Task completion in testing' },
      { metric: '3×',   label: 'Faster booking vs. DM flow' },
    ],
    prev: null,
    next: 'aura',
  },

  aura: {
    id: 'aura',
    title: 'Aura',
    emoji: '✨',
    tagline: 'Gamified Emotional Wellness App',
    category: 'Mobile · iOS & Android',
    year: '2025',
    role: 'Product Designer — UI/UX & Motion',
    duration: '2.5 months',
    color: '#3ECFBF',
    colorPale: '#D4F5F1',
    tools: ['Figma', 'Principle', 'Lottie', 'Prototyping', 'User Interviews'],
    overview: 'Aura is a gamified emotional-wellness app centred around an animated AI companion that grows with the user. Daily mood check-ins, a streak system, and an in-app energy economy create the habit loops that keep users engaged and reflecting.',
    problem: 'Most wellness apps feel clinical and chore-like. Users log mood data but never feel a connection to the experience. High churn after day 7 is the norm. Aura needed to feel like a friend, not a form.',
    solution: 'A character-driven experience where the AI companion reacts to the emotional state of the user, celebrates wins, and gently nudges on missed days — backed by a gamified economy to reward consistency without creating anxiety.',
    process: [
      { step: '01', label: 'Research',      icon: '🔍', desc: 'Analysed churn data from 3 competing wellness apps. Conducted 10 diary studies over 2 weeks to understand daily emotional rhythms.' },
      { step: '02', label: 'Character Design', icon: '🐣', desc: 'Collaborated with an illustrator to define the companion\'s personality — warm, curious, non-judgmental. Defined 12 emotional states with corresponding animations.' },
      { step: '03', label: 'Economy Design', icon: '🪙', desc: 'Designed the energy/reward loop: check-ins earn Aura Points, streaks unlock companion evolutions, store items are cosmetic — never paywalled core features.' },
      { step: '04', label: 'UI Design',     icon: '✏️', desc: 'Soft palette, sketch-faithful layouts. Prioritised white space and breathing room to counteract the anxiety that dense wellness UIs often create.' },
      { step: '05', label: 'Motion',        icon: '🎞️', desc: 'Scripted 18 Lottie animations for companion reactions and micro-interactions. Motion is the key differentiator from static-screen competitors.' },
    ],
    screens: [
      { name: 'Home / Companion', bg: 'linear-gradient(145deg,#3ECFBF,#0D9488)', type: 'phone' },
      { name: 'Daily Check-in',   bg: 'linear-gradient(145deg,#5EEAD4,#0F766E)', type: 'phone' },
      { name: 'Progress Journal', bg: 'linear-gradient(145deg,#6EE7B7,#059669)', type: 'phone' },
      { name: 'Reward Store',     bg: 'linear-gradient(145deg,#34D399,#047857)', type: 'phone' },
    ],
    outcomes: [
      { metric: '38',   label: 'Screens designed' },
      { metric: '18',   label: 'Lottie animations scripted' },
      { metric: '4.8★', label: 'Avg. prototype test rating' },
      { metric: '↓62%', label: 'Projected Day-7 churn vs. baseline' },
    ],
    prev: 'inklab',
    next: 'pulse',
  },

  pulse: {
    id: 'pulse',
    title: 'Pulse',
    emoji: '📊',
    tagline: 'Analytics Dashboard for Modern Teams',
    category: 'Web · SaaS Dashboard',
    year: '2024',
    role: 'Product Designer — UI/UX & Handoff',
    duration: '2 months',
    color: '#4D96FF',
    colorPale: '#DBEAFE',
    tools: ['Figma', 'FigJam', 'Design Tokens', 'Storybook', 'Zeroheight'],
    overview: 'Pulse is a Mixpanel-style analytics dashboard for growth and product teams. It makes dense behavioural data legible through a clear visual hierarchy, a restrained colour palette, and a report-builder that non-technical users can drive without SQL.',
    problem: 'The existing dashboard overwhelmed users with data density: 14 charts on one screen, no clear hierarchy, and a report builder only engineers understood. Key metrics were buried; time-to-insight averaged 8 minutes.',
    solution: 'A restructured information architecture that surfaces the 4 metrics each role cares about on first load, a block-based report builder anyone can use, and a design system that makes the engineering handoff transparent.',
    process: [
      { step: '01', label: 'Audit',         icon: '🔎', desc: 'Ran a full heuristic evaluation of the existing dashboard. Tagged 31 issues across visibility, control, consistency, and error-prevention principles.' },
      { step: '02', label: 'User Flows',    icon: '🗺️', desc: 'Mapped 5 primary jobs-to-be-done. Collapsed 14 screens into 4 core views based on task frequency and role-based needs.' },
      { step: '03', label: 'IA & Layout',   icon: '📐', desc: 'Defined sidebar navigation, contextual filters, and a persistent KPI strip. Established an 8-pt grid and 4-column layout system.' },
      { step: '04', label: 'Design System', icon: '🧩', desc: 'Built 80+ chart, table, and data components with Figma Variables for light/dark modes. Published to Zeroheight for the dev team.' },
      { step: '05', label: 'Handoff',       icon: '📦', desc: 'Delivered an 8-slide editorial case study, redline specs for every component, and a Storybook-ready token file. Zero back-and-forth post-handoff.' },
    ],
    screens: [
      { name: 'Dashboard Overview', bg: 'linear-gradient(145deg,#4D96FF,#2563EB)', type: 'browser' },
      { name: 'Funnel Analysis',    bg: 'linear-gradient(145deg,#60A5FA,#1D4ED8)', type: 'browser' },
      { name: 'Report Builder',     bg: 'linear-gradient(145deg,#93C5FD,#1E40AF)', type: 'browser' },
      { name: 'User Explorer',      bg: 'linear-gradient(145deg,#3B82F6,#1E3A8A)', type: 'browser' },
    ],
    outcomes: [
      { metric: '↓76%', label: 'Time-to-insight (8 min → 2 min)' },
      { metric: '80+',  label: 'Design system components' },
      { metric: '0',    label: 'Post-handoff design revisions' },
      { metric: '31',   label: 'Heuristic issues resolved' },
    ],
    prev: 'aura',
    next: 'thoroi',
  },

  thoroi: {
    id: 'thoroi',
    title: 'Thợ Ơi!',
    emoji: '🔧',
    tagline: 'Home-Repair Booking App — Redesign',
    category: 'Mobile · Vietnamese Market',
    year: '2024',
    role: 'Product Designer — UX Audit & Redesign',
    duration: '6 weeks',
    color: '#FF6B6B',
    colorPale: '#FFE8E8',
    tools: ['Figma', 'Maze', 'Hotjar', 'Nielsen Heuristics', 'User Testing'],
    overview: 'Thợ Ơi! is a Vietnamese home-repair booking platform connecting homeowners with vetted tradespeople. I conducted a full Nielsen heuristic audit and redesigned five core screens to reduce friction between search and confirmed booking.',
    problem: 'User drop-off was highest at the service-selection and checkout steps. The original UI used inconsistent patterns, unclear affordances, and a 7-step booking flow that required users to context-switch between three separate confirmation screens.',
    solution: 'A redesigned search-to-book flow that consolidates 7 steps into 3, uses progressive disclosure to surface only what is needed at each stage, and introduces social-proof signals (ratings, real-time availability) at the right moments.',
    process: [
      { step: '01', label: 'Heuristic Audit',  icon: '📋', desc: 'Evaluated the existing app against Nielsen\'s 10 heuristics. Found 24 violations; 9 were severity-3 (major usability problems causing task failure).' },
      { step: '02', label: 'Hotjar Analysis',  icon: '🔥', desc: 'Analysed session recordings and heatmaps. Confirmed 3 rage-click hotspots and identified the exact screens where 68% of users abandoned booking.' },
      { step: '03', label: 'User Interviews',  icon: '🎙️', desc: 'Interviewed 8 app users and 4 tradespeople. Learned that trust signals (reviews, ID verification badges) were the #1 factor in booking decisions.' },
      { step: '04', label: 'Redesign',         icon: '✏️', desc: 'Redesigned 5 core screens: search, service listing, tradesperson profile, booking form, and confirmation. Collapsed 7 steps to 3 with a persistent progress indicator.' },
      { step: '05', label: 'Validation',       icon: '✅', desc: 'Unmoderated Maze test with 15 participants. Booking task completion rose from 54% to 91%. Average time-on-task dropped from 4m 12s to 1m 38s.' },
    ],
    screens: [
      { name: 'Home & Search',     bg: 'linear-gradient(145deg,#FF6B6B,#DC2626)', type: 'phone' },
      { name: 'Service Listing',   bg: 'linear-gradient(145deg,#F87171,#B91C1C)', type: 'phone' },
      { name: 'Pro Profile',       bg: 'linear-gradient(145deg,#FF9F1C,#D97706)', type: 'phone' },
      { name: 'Booking & Confirm', bg: 'linear-gradient(145deg,#FBBF24,#B45309)', type: 'phone' },
    ],
    outcomes: [
      { metric: '+37%', label: 'Booking completion rate' },
      { metric: '↓61%', label: 'Time-on-task (4m → 1m38s)' },
      { metric: '24',   label: 'Heuristic violations resolved' },
      { metric: '3',    label: 'Steps to book (was 7)' },
    ],
    prev: 'pulse',
    next: null,
  },
};
